name: Manga Chapter Notifier

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: manga-checker
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run manga checker every 1 minute for 5 minutes
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          for i in 1 2 3 4 5
          do
            echo "Check number $i"
            python checker.py

            if [ "$i" != "5" ]; then
              sleep 60
            fi
          done

      - name: Save updated chapter state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if [ -f seen_chapters.json ]; then
            git add seen_chapters.json

            if git diff --cached --quiet; then
              echo "No state changes."
            else
              git commit -m "Update seen chapters"
              git push
            fi
          else
            echo "seen_chapters.json not found."
          fi
